version: "3.4"

services:
  app:
    extends:
      file: docker-compose.base.yml
      service: prod_app
    volumes:
        - static_volume:/opt/code/static
        - shm:/dev/shm

  nginx:
    extends:
      file: docker-compose.base.yml
      service: nginx
    volumes:
      - static_volume:/opt/code/static
      - shm:/dev/shm
    depends_on:
      - app

  ping:
    extends:
      file: docker-compose.base.yml
      service: ping
    depends_on:
      - app

  cron:
    extends:
      file: docker-compose.base.yml
      service: cron
    depends_on:
      - app

  ssh:
    extends:
      file: docker-compose.base.yml
      service: ssh
    environment:
      - SERVICE=app:8000
    volumes:
      - static_volume:/opt/code/static
      - shm:/dev/shm
    depends_on:
      - app

  guacd:
    image: guacamole/guacd

  guac_proxy:
    image: vfse_app
    env_file:
      - ./docker/env.db
      - ./.env
    container_name: guac_proxy
    depends_on:
      - app
      - guacd
    command: "uvicorn proxy.guac:app --host 0.0.0.0"

volumes:
  static_volume:
  shm:
