services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    env_file:
      - ./docker/env.db
      - ./.env
    container_name: vfse
    command: bash -c 'python manage.py runserver 0.0.0.0:8000'

  prod_app:
    extends:
      service: app
    build:
      context: .
      dockerfile: ./docker/prod.Dockerfile
    command: ./docker/scripts/run-gunicorn

  ping:
    image: vfse_app
    env_file:
      - ./docker/env.db
      - ./.env
    command: bash -c "python manage.py ping"
    depends_on:
      - app

  cron:
    image: vfse_app
    command: bash -c "cron -f"

  nginx:
    build: ./nginx
    restart: always
    ports:
      - 80:80
      - 443:443

  db:
    image: postgres:13.4-alpine
    env_file:
      - ./docker/env.db

  ssh:
    build:
      context: .
      dockerfile: ./webssh/Dockerfile
    container_name: vfse_ssh
    command: ./docker/scripts/run-webssh
    env_file:
      - ./.env
    expose:
      - 8888
