version: "3.4"

services:
  db:
    extends:
      file: docker-compose.base.yml
      service: db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    extends:
      file: docker-compose.base.yml
      service: app
    ports:
      - "8000:8000"
    volumes:
      - .:/opt/code
      - dist:/opt/code/frontend/dist/
    depends_on:
      - db

  guac_proxy:
    image: vfse_app
    ports:
      - "8001:8001"
    command: bash -c 'uvicorn --reload --port 8001 guac:app'

  html_proxy:
    image: vfse_app
    ports:
      - "8002:8002"
    command: bash -c 'uvicorn --reload --port 8002 proxy.service:app'

  frontend:
    image: vfse_app
    volumes:
      - .:/opt/code
      - dist:/opt/code/frontend/dist/
    depends_on:
      - db
    command: bash -c 'npm run start'

  ping:
    extends:
      file: docker-compose.base.yml
      service: ping
    depends_on:
      - app

  cron:
    extends:
      file: docker-compose.base.yml
      service: cron
    depends_on:
      - app

  ssh:
    extends:
      file: docker-compose.base.yml
      service: ssh
    volumes:
      - .:/opt/code
    depends_on:
      - app
    ports:
      - "8888:8888"

  nginx:
    build:
      context: ./nginx
      dockerfile: local.Dockerfile
    restart: always
    ports:
      - 80:80
    volumes:
      - dist:/opt/code/frontend/dist/

volumes:
  dist:
  pgdata:
