version: "3.4"

services:
  db:
    image: postgres:13.4
    env_file:
      - ./docker/env.db

  app:
    build:
      context: .
      dockerfile: ./docker/prod.Dockerfile
    env_file:
      - ./docker/env.db
      - ./.env
    container_name: vfse
    volumes:
      - static_volume:/opt/code/static
      - shm:/dev/shm
    command: ./docker/scripts/run-gunicorn
    depends_on:
      - db

  nginx:
    build: ./nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - static_volume:/opt/code/static
      - shm:/dev/shm
    depends_on:
      - app

volumes:
  static_volume:
  shm:
