version: "3.4"

services:
  app:
    extends:
      file: docker-compose.base.yml
      service: prod_app
    volumes:
        - static_volume:/opt/code/static
        - shm:/dev/shm

  nginx:
    extends:
      file: docker-compose.base.yml
      service: nginx
    volumes:
      - static_volume:/opt/code/static
      - shm:/dev/shm
    depends_on:
      - app

  ping:
    extends:
      file: docker-compose.base.yml
      service: ping
    restart: always
    depends_on:
      - app

  cron:
    extends:
      file: docker-compose.base.yml
      service: cron
    depends_on:
      - app

  ssh:
    extends:
      file: docker-compose.base.yml
      service: ssh
    environment:
      - SERVICE=app:8000
    volumes:
      - static_volume:/opt/code/static
      - shm:/dev/shm
    depends_on:
      - app

  vnc_proxy:
    image: vfse_app
    env_file:
      - ./docker/env.db
      - ./.env
    container_name: vnc_proxy
    depends_on:
      - app
    command: bash -c 'uvicorn --host 0.0.0.0 --port 8001 proxy.vnc:app'

  html_proxy:
    image: vfse_app
    env_file:
      - ./docker/env.db
      - ./.env
    container_name: html_proxy
    depends_on:
      - app
    command: bash -c 'uvicorn --host 0.0.0.0 --port 8002 proxy.service:app'

  guacd:
    image: guacamole/guacd

  guac_proxy:
    image: vfse_app
    env_file:
      - ./docker/env.db
      - ./.env
    container_name: guac_proxy
    depends_on:
      - app
      - guacd
    command: bash -c 'uvicorn --host 0.0.0.0 --port 8003 proxy.guac:app'

volumes:
  static_volume:
  shm:
