version: "3.4"

services:
  db:
    extends:
      file: docker-compose.base.yml
      service: db

  app:
    extends:
      file: docker-compose.base.yml
      service: prod_app
    volumes:
        - static_volume:/opt/code/static
        - shm:/dev/shm
    depends_on:
      - db

  nginx:
    extends:
      file: docker-compose.base.yml
      service: nginx
    volumes:
      - static_volume:/opt/code/static
      - shm:/dev/shm
    depends_on:
      - app

  ping:
    extends:
      file: docker-compose.base.yml
      service: ping
    depends_on:
      - app

volumes:
  static_volume:
  shm:
