version: "3.4"

services:
  db:
    extends:
      file: docker-compose.base.yml
      service: db

  app:
    extends:
      file: docker-compose.base.yml
      service: prod_app
    volumes:
        - static_volume:/opt/code/static
        - shm:/dev/shm
    depends_on:
      - db

  cron:
    extends:
      file: docker-compose.base.yml
      service: cron
    depends_on:
      - app
  nginx:
    extends:
      file: docker-compose.base.yml
      service: nginx
    volumes:
      - static_volume:/opt/code/static
      - shm:/dev/shm
    depends_on:
      - ssh

  ping:
    extends:
      file: docker-compose.base.yml
      service: ping

  ssh:
    extends:
      file: docker-compose.base.yml
      service: ssh
    depends_on:
      - app
    expose:
      - 8888

volumes:
  static_volume:
  shm:
