version: "3.4"

services:
  db:
    extends:
      file: docker-compose.base.yml
      service: db
    ports:
      - 127.0.0.1:5432:5432

  app:
    extends:
      file: docker-compose.base.yml
      service: app
    ports:
      - "8000:8000"
    volumes:
      - .:/opt/code
      - dist:/opt/code/frontend/dist/
    depends_on:
      - db

  frontend:
    image: vfse_app
    volumes:
      - .:/opt/code
      - dist:/opt/code/frontend/dist/
    depends_on:
      - db
    command: bash -c 'npm run start'

  ping:
    extends:
      file: docker-compose.base.yml
      service: ping
    depends_on:
      - app

  cron:
    extends:
      file: docker-compose.base.yml
      service: cron
    depends_on:
      - app

  ssh:
    extends:
      file: docker-compose.base.yml
      service: ssh
    volumes:
      - .:/opt/code
    depends_on:
      - app
    ports:
      - "8888:8888"

volumes:
  dist:
