version: "3.4"

services:
  db:
    extends:
      file: docker-compose.base.yml
      service: db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    extends:
      file: docker-compose.base.yml
      service: app
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/opt/code/static
      - .:/opt/code
      - dist:/opt/code/frontend/dist/
    depends_on:
      - db

  vnc_proxy:
    image: vfse_app
    volumes:
      - .:/opt/code
    ports:
      - "8001:8001"
    command: bash -c 'uvicorn --reload --host 0.0.0.0 --port 8001 proxy.vnc:app'

  html_proxy:
    image: vfse_app
    volumes:
      - .:/opt/code
    ports:
      - "8002:8002"
    command: bash -c 'uvicorn --reload --host 0.0.0.0 --port 8002 proxy.service:app'

  guacd:
    image: guacamole/guacd

  guac_proxy:
    image: vfse_app
    env_file:
      - ./docker/env.db
      - ./.env
    container_name: guac_proxy
    volumes:
      - .:/opt/code
    ports:
      - "8003:8003"
    depends_on:
      - app
      - guacd
    command: bash -c 'uvicorn --host 0.0.0.0 --port 8003 proxy.guac:app'

  frontend:
    image: vfse_app
    volumes:
      - .:/opt/code
      - dist:/opt/code/frontend/dist/
    depends_on:
      - db
    command: bash -c 'npm run start'

  ping:
    extends:
      file: docker-compose.base.yml
      service: ping
    depends_on:
      - app

  cron:
    extends:
      file: docker-compose.base.yml
      service: cron
    depends_on:
      - app

  ssh:
    extends:
      file: docker-compose.base.yml
      service: ssh
    volumes:
      - .:/opt/code
    depends_on:
      - app
    ports:
      - "8888:8888"

  nginx:
    build:
      context: ./nginx
      dockerfile: local.Dockerfile
    restart: always
    ports:
      - "9090:80"
    volumes:
      - static_volume:/opt/code/static
    depends_on:
      - app

volumes:
  dist:
  static_volume:
  pgdata:
