version: "3.4"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/prod.Dockerfile
    env_file:
      - ./.env
    container_name: vfse
    volumes:
      - static_volume:/opt/code/static
      - shm:/dev/shm
    command: ./docker/scripts/run-gunicorn

  nginx:
    build: ./nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/opt/code/static
      - shm:/dev/shm
    depends_on:
      - app

  ping:
    image: vfse_app
    env_file:
      - ./.env
    command: bash -c "python manage.py ping 300"
    depends_on:
      - app

volumes:
  static_volume:
  shm:
