# Generated by Django 3.2.8 on 2021-11-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_supermanager",
            field=models.BooleanField(default=False),
        ),
    ]
