# Generated by Django 3.2.8 on 2021-11-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_auto_20211102_1044"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthnetwork",
            name="name",
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.CharField(
                choices=[
                    ("fse-admin", "FSE Admin"),
                    ("customer-admin", "Customer Admin"),
                    ("user-admin", "User Admin"),
                    ("fse", "Field Service Engineer"),
                    ("end-user", "End User"),
                    ("view-only", "View Only"),
                    ("one-time", "One Time"),
                    ("cryo", "Cryo"),
                    ("cryo-fse", "Cryo FSE"),
                    ("cryo-admin", "Cryo Admin"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="usermodality",
            constraint=models.UniqueConstraint(
                fields=("user", "modality"), name="unique_user_modality"
            ),
        ),
    ]
