# Generated by Django 3.2.8 on 2021-11-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_site_organization_health_network"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentation",
            name="documenation",
            field=models.FileField(upload_to="documentation/"),
        ),
        migrations.AlterField(
            model_name="healthnetwork",
            name="logo",
            field=models.ImageField(upload_to="health-network/logo/"),
        ),
        migrations.AlterField(
            model_name="manufacturerimage",
            name="image",
            field=models.ImageField(upload_to="manufacture/"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="banner",
            field=models.ImageField(
                blank=True, null=True, upload_to="organization/banner/"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="organization/logo/"
            ),
        ),
        migrations.AlterField(
            model_name="systemimage",
            name="image",
            field=models.ImageField(blank=True, default="", upload_to="system-image/"),
        ),
    ]
