# Generated by Django 3.2.8 on 2021-11-04 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_membership_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="manufacturer",
        ),
        migrations.RemoveField(
            model_name="product",
            name="modality",
        ),
        migrations.CreateModel(
            name="ManufacturerModality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.manufacturer",
                    ),
                ),
                (
                    "modality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.modality"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="manufacturer_modality",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.manufacturermodality",
            ),
        ),
    ]
