# Generated by Django 3.2.8 on 2021-11-04 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_auto_20211104_0830"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="manufacturer_modality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.manufacturermodality",
            ),
        ),
    ]
