# Generated by Django 3.2.8 on 2021-11-11 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_product_manufacturer_modality"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Notes",
            new_name="Note",
        ),
        migrations.AlterModelOptions(
            name="modality",
            options={"verbose_name_plural": "Modalities"},
        ),
        migrations.AlterModelOptions(
            name="usermodality",
            options={"verbose_name_plural": "User modalities"},
        ),
    ]
