# Generated by Django 3.2.8 on 2021-11-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_profile_manager"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="healthnetwork",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_health_network_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="manufacturer",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_manufacturer_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="manufacturermodality",
            constraint=models.UniqueConstraint(
                fields=("manufacturer", "modality"), name="unique_manufacturer_modality"
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                fields=("user", "organization", "role"),
                name="unique_user_organization_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="modality",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_modality_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationhealthnetwork",
            constraint=models.UniqueConstraint(
                fields=("organization", "health_network"),
                name="unique_organization_health_network",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("manufacturer_modality", "name"),
                name="unique_manufacturer_modality_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="seat",
            constraint=models.UniqueConstraint(
                fields=("system", "organization"), name="unique_system_organization"
            ),
        ),
        migrations.AddConstraint(
            model_name="site",
            constraint=models.UniqueConstraint(
                fields=("organization_health_network", "name"),
                name="unique_organization_health_network_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="userhealthnetwork",
            constraint=models.UniqueConstraint(
                fields=("user", "health_network"), name="unique_user_health_network"
            ),
        ),
        migrations.AddConstraint(
            model_name="usersite",
            constraint=models.UniqueConstraint(
                fields=("user", "site"), name="unique_user_site"
            ),
        ),
    ]
