# Generated by Django 3.2.8 on 2021-11-19 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_add_unique_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="system",
            name="connection_monitoring",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="system",
            name="documentation_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="system",
            name="location_in_building",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="system",
            name="other",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="system",
            name="serial_number",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="system",
            name="system_contact_info",
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="system",
            name="system_option",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="SystemDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "his_ris_info_ip",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                (
                    "his_ris_info_ae_title",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "his_ris_info_title",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("his_ris_info_port", models.IntegerField(blank=True, null=True)),
                ("dicom_info_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "dicom_info_ae_title",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "dicom_info_title",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("dicom_info_port", models.IntegerField(blank=True, null=True)),
                (
                    "mri_embedded_parameters_helium",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "mri_embedded_parameters_magnet_pressure",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="core.system"
                    ),
                ),
            ],
        ),
    ]
