# Generated by Django 3.2.8 on 2021-11-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_system_detail_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.EmailField(
                error_messages={"unique": "A user with that username already exists."},
                max_length=254,
                unique=True,
                verbose_name="username",
            ),
        ),
    ]
