# Generated by Django 3.2.8 on 2021-11-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_alter_user_username"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="organization",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_organization_name"
            ),
        ),
    ]
