# Generated by Django 3.2.8 on 2021-11-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_auto_20211129_0753"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthnetwork",
            name="logo",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="manufacturerimage",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="banner",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="logo",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="systemimage",
            name="image",
            field=models.URLField(),
        ),
    ]
