# Generated by Django 3.2.8 on 2021-11-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_auto_20211130_0540"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="appearance",
            field=models.JSONField(default=dict),
        ),
    ]
