# Generated by Django 3.2.8 on 2021-12-02 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_organization_appearance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="background_color",
        ),
    ]
