# Generated by Django 3.2.8 on 2021-12-04 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_remove_manufacturer_modality"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="manufacturer",
            name="unique_manufacturer_name",
        ),
        migrations.RemoveField(
            model_name="documentation",
            name="documenation",
        ),
        migrations.RemoveField(
            model_name="documentation",
            name="product",
        ),
        migrations.RemoveField(
            model_name="system",
            name="documentation_link",
        ),
        migrations.RemoveField(
            model_name="system",
            name="modality",
        ),
        migrations.RemoveField(
            model_name="system",
            name="product",
        ),
        migrations.AddField(
            model_name="documentation",
            name="url",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="manufacturer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.manufacturer",
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="name",
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=32),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("name", "manufacturer"), name="unique_product_name_manufacturer"
            ),
        ),
        migrations.AddField(
            model_name="productmodel",
            name="documentation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.documentation",
            ),
        ),
        migrations.AddField(
            model_name="productmodel",
            name="modality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.modality"
            ),
        ),
        migrations.AddField(
            model_name="productmodel",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.product"
            ),
        ),
        migrations.AddField(
            model_name="system",
            name="product_model",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.productmodel",
            ),
        ),
        migrations.AddConstraint(
            model_name="productmodel",
            constraint=models.UniqueConstraint(
                fields=("product", "model"), name="unique_product_model"
            ),
        ),
    ]
