# Generated by Django 3.2.8 on 2021-12-04 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_shift_to_new_architecture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentation",
            name="url",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="manufacturer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.manufacturer"
            ),
        ),
        migrations.AlterField(
            model_name="system",
            name="product_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.productmodel"
            ),
        ),
    ]
