# Generated by Django 3.2.8 on 2021-12-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_profile_view_only"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="one_time_complete",
            field=models.BooleanField(default=False),
        ),
    ]
