# Generated by Django 3.2.8 on 2021-12-15 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20211213_0404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthnetwork',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='manufacturerimage',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='modality',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Modalities'},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='system',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='systemimage',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id']},
        ),
    ]
