# Generated by Django 3.2.8 on 2021-12-15 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20211215_1012'),
        ('core', '0035_auto_20211215_1039'),
    ]

    operations = [
    ]
