# Generated by Django 3.2.8 on 2021-12-16 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_merge_0035_auto_20211215_1012_0035_auto_20211215_1039'),
        ('core', '0036_organization_is_customer'),
    ]

    operations = [
    ]
