# Generated by Django 3.2.8 on 2021-12-17 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_auto_20211217_0152"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="health_network",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.healthnetwork",
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sites",
                to="core.organization",
            ),
        ),
    ]
