# Generated by Django 3.2.8 on 2021-12-17 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_fix_nulls_in_site"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="membership",
            name="unique_user_organization_role",
        ),
        migrations.RemoveConstraint(
            model_name="userhealthnetwork",
            name="unique_user_health_network",
        ),
        migrations.RemoveField(
            model_name="organizationhealthnetwork",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="userhealthnetwork",
            name="health_network",
        ),
        migrations.AddField(
            model_name="userhealthnetwork",
            name="organization_health_network",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.organizationhealthnetwork",
            ),
        ),
        migrations.AddField(
            model_name="userhealthnetwork",
            name="role",
            field=models.CharField(
                choices=[
                    ("fse-admin", "FSE Admin"),
                    ("customer-admin", "Customer Admin"),
                    ("user-admin", "User Admin"),
                    ("fse", "Field Service Engineer"),
                    ("end-user", "End User"),
                    ("view-only", "View Only"),
                    ("one-time", "One Time"),
                    ("cryo", "Cryo"),
                    ("cryo-fse", "Cryo FSE"),
                    ("cryo-admin", "Cryo Admin"),
                ],
                default="fse",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="organization",
            field=models.ForeignKey(
                limit_choices_to={"is_customer": True},
                on_delete=django.db.models.deletion.CASCADE,
                to="core.organization",
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                fields=("user", "organization"), name="unique_user_organization"
            ),
        ),
        migrations.AddConstraint(
            model_name="userhealthnetwork",
            constraint=models.UniqueConstraint(
                fields=("user", "organization_health_network"),
                name="unique_user_organization_health_network",
            ),
        ),
    ]
