# Generated by Django 3.2.8 on 2021-12-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_membership_parent'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='membership',
            name='unique_user_organization_role',
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'organization'), name='unique_user_organization'),
        ),
    ]
