# Generated by Django 3.2.8 on 2021-12-18 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_userhealthnetwork_organization_health_network'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='logo',
        ),
    ]
