# Generated by Django 3.2.8 on 2021-12-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_auto_20211218_0853"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="site",
            name="unique_health_network_site_name",
        ),
        migrations.RemoveField(
            model_name="site",
            name="health_network",
        ),
        migrations.AddConstraint(
            model_name="site",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"), name="unique_organization_site_name"
            ),
        ),
        migrations.DeleteModel(
            name="HealthNetwork",
        ),
    ]
