# Generated by Django 3.2.8 on 2021-12-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_remove_health_network_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='meta',
            field=models.JSONField(default=dict),
        ),
    ]
