# Generated by Django 3.2.8 on 2021-12-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_profile_meta"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="under_review",
            field=models.BooleanField(default=False),
        ),
    ]
