# Generated by Django 4.0 on 2021-12-28 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_alter_system_site"),
    ]

    operations = [
        migrations.AlterField(
            model_name="system",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="systems",
                to="core.site",
            ),
        ),
    ]
