# Generated by Django 4.0 on 2022-01-05 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_alter_membership_organization"),
        ("core", "0051_alter_membership_organization_and_more"),
    ]

    operations = []
