# Generated by Django 4.0 on 2022-01-05 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_alter_product_options"),
        ("core", "0052_merge_20220105_1124"),
    ]

    operations = []
