# Generated by Django 4.0 on 2022-01-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_merge_20220105_1443'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='system',
            constraint=models.UniqueConstraint(fields=('name', 'site'), name='unique_system'),
        ),
    ]
