# Generated by Django 4.0 on 2022-01-06 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_merge_20220105_1443"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productmodel",
            options={"ordering": ["-id"]},
        ),
    ]
