# Generated by Django 4.0 on 2022-01-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_alter_productmodel_options"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="system",
            constraint=models.UniqueConstraint(
                fields=("name", "site"), name="unique_system"
            ),
        ),
    ]
