# Generated by Django 4.0 on 2022-01-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_alter_membership_role_alter_userhealthnetwork_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='documentation_url',
            field=models.BooleanField(default=False),
        ),
    ]
