# Generated by Django 4.0 on 2022-01-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0059_usermodality_organization_usersite_organization_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="documentation_url",
            field=models.BooleanField(default=False),
        ),
    ]
