# Generated by Django 4.0 on 2022-01-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_profile_documentation_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_lambda_user',
            field=models.BooleanField(default=False),
        ),
    ]
