# Generated by Django 4.0 on 2022-01-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0061_alter_system_grafana_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(default="", max_length=32),
        ),
    ]
