# Generated by Django 4.0 on 2022-03-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0066_modality_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_request_user",
            field=models.BooleanField(default=False),
        ),
    ]
