# Generated by Django 4.0 on 2022-02-16 06:40

from django.db import migrations

from core.models import ModalityType


def add_modalities(apps, schema_editor):
    modality_model = apps.get_model("core", "Modality")
    for choice in ModalityType.choices:
        modality_model.objects.create(name=choice[1], group=choice[0])


def reverse_action(apps, schema_editor):
    apps.get_model("core", "Product").objects.all().delete()
    apps.get_model("core", "Modality").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0066_modality_group"),
    ]

    operations = [migrations.RunPython(add_modalities, reverse_code=reverse_action)]
