# Generated by Django 4.0 on 2022-03-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0067_user_is_request_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="system",
            name="asset_number",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="system",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="system",
            name="local_ae_title",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="system",
            name="software_version",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
