# Generated by Django 4.0 on 2022-04-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0068_alter_system_asset_number_alter_system_ip_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="system",
            name="last_successful_ping_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
