# Generated by Django 4.0 on 2022-04-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0069_alter_system_last_successful_ping_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="system",
            name="ssh_password",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_remote_user",
            field=models.BooleanField(default=False),
        ),
    ]
