# Generated by Django 4.0 on 2022-04-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0070_system_ssh_password_user_is_remote_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="system",
            name="chatbot_content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
