# Generated by Django 4.0 on 2022-04-26 10:10
import os

from django.db import migrations


def chatbot_initial_content(apps, schema_editor):
    System = apps.get_model("core", "System")
    with open(os.getcwd() + "/core/openapi/data/content.txt") as f:
        prompt = f.read()

    for system in System.objects.all():
        system.chatbot_content = prompt
        system.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0071_system_chatbot_content"),
    ]

    operations = [
        migrations.RunPython(chatbot_initial_content, migrations.RunPython.noop),
    ]
