# Generated by Django 4.0 on 2022-05-26 05:12
from django.templatetags.static import static

from django.db import migrations
from django.db.models import Q


def change_profile_picture(apps, schema_edtor):
    Profile = apps.get_model("core", "Profile")

    for user_profile in Profile.objects.exclude(
        Q(user__is_lambda_user=True),
        Q(user__is_request_user=True),
        Q(user__is_remote_user=True),
    ).filter(
        Q(meta__profile_picture="") | Q(meta__profile_picture__icontains="kindpng")
    ):
        user_profile.meta["profile_picture"] = static("assets/profile.png")
        user_profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0072_auto_20220426_1010"),
    ]

    operations = [
        migrations.RunPython(change_profile_picture, migrations.RunPython.noop)
    ]
