# Generated by Django 4.0 on 2022-05-31 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0073_auto_20220526_0512"),
    ]

    operations = [
        migrations.AddField(
            model_name="system",
            name="ssh_user",
            field=models.CharField(default="root", max_length=25),
        ),
    ]
