# Generated by Django 4.0.5 on 2022-07-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0075_system_show_dicom_system_show_ris"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="system",
            name="show_dicom",
        ),
        migrations.RemoveField(
            model_name="system",
            name="show_ris",
        ),
        migrations.AddField(
            model_name="modality",
            name="show_dicom",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="modality",
            name="show_ris",
            field=models.BooleanField(default=False),
        ),
    ]
