# Generated by Django 4.1 on 2022-09-04 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0076_alter_productmodel_documentation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="is_view_only",
        ),
    ]
