# Generated by Django 4.1.2 on 2022-11-29 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0082_routerlocation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="routerlocation",
            name="updated_at",
        ),
    ]
