# Generated by Django 4.1.5 on 2023-01-31 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_system_vnc_ip_system_vnc_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system',
            name='vnc_ip',
        ),
        migrations.AddField(
            model_name='system',
            name='vnc_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
