# Generated by Django 4.1.5 on 2023-02-01 09:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0086_remove_system_vnc_ip_system_vnc_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="system",
            name="vnc_password",
        ),
    ]
