# Generated by Django 4.1.5 on 2023-02-08 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0087_remove_system_vnc_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="system",
            name="vnc_url",
        ),
    ]
