# Generated by Django 4.1.6 on 2023-02-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0089_system_access_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="system",
            name="vnc_port",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
