# Generated by Django 4.1.6 on 2023-03-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0091_alter_system_vnc_port"),
    ]

    operations = [
        migrations.AddField(
            model_name="system",
            name="service_page_url",
            field=models.CharField(default="http://ip_address/service", max_length=512),
        ),
    ]
