# Generated by Django 4.1.6 on 2023-03-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0092_system_service_page_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="system",
            name="service_page_url",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
