# Generated by Django 4.1.7 on 2023-03-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0093_alter_system_service_page_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersystem",
            name="read_only",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
