# Generated by Django 4.1.7 on 2023-03-15 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0094_usersystem_read_only"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersystem",
            name="read_only",
        ),
    ]
