# Generated by Django 4.2 on 2023-04-18 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0096_system_telnet_password_system_telnet_username_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="system",
            name="access_url",
        ),
    ]
