# Generated by Django 4.2 on 2023-04-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0097_remove_system_access_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="system",
            name="ssh_user",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
