# Generated by Django 4.0 on 2022-02-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vfse", "0003_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="folder",
            name="categories",
            field=models.ManyToManyField(related_name="categories", to="vfse.Category"),
        ),
    ]
