# Generated by Django 4.0 on 2022-03-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vfse", "0006_document_categories_alter_folder_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
