# Generated by Django 4.0 on 2022-03-28 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vfse", "0008_category_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="document_link",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="folder",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="vfse.folder",
            ),
        ),
    ]
