# Generated by Django 4.0 on 2022-04-12 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0070_system_ssh_password_user_is_remote_user"),
        ("vfse", "0011_follower_topic_recentactivity_follower_topic_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comments",
            new_name="Comment",
        ),
    ]
