# Generated by Django 4.0 on 2022-04-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vfse", "0012_rename_comments_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="topics", to="vfse.Category"
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="followed_topics", to="vfse.Follower"
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
