# Generated by Django 4.0 on 2022-04-15 05:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vfse", "0013_alter_topic_categories_alter_topic_followers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="followed_topics", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="Follower",
        ),
    ]
