# Generated by Django 4.0 on 2022-04-18 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0070_system_ssh_password_user_is_remote_user"),
        ("vfse", "0014_alter_topic_followers_delete_follower"),
    ]

    operations = [
        migrations.AddField(
            model_name="recentactivity",
            name="topic",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity",
                to="vfse.topic",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="comment",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="vfse.topic",
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topics",
                to="core.user",
            ),
        ),
    ]
