# Generated by Django 4.0 on 2022-04-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vfse", "0016_workorder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
