# Generated by Django 4.0 on 2022-04-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vfse", "0017_alter_topic_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workorder",
            name="work_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
