# Generated by Django 4.0 on 2022-05-31 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vfse", "0019_comment_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recentactivity",
            name="action",
            field=models.CharField(max_length=530),
        ),
    ]
