# Generated by Django 4.0 on 2022-06-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vfse", "0021_alter_topic_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workorder",
            name="work_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
