# Generated by Django 4.0.5 on 2022-07-29 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vfse", "0022_alter_workorder_work_started_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-id"]},
        ),
    ]
