# Generated by Django 4.1 on 2022-09-01 09:21

from django.db import migrations


def default_categories(apps, schema_editor):
    Document = apps.get_model('vfse', 'Document')
    for document in Document.objects.all():
        person.name = '%s %s' % (person.first_name, person.last_name)
        person.save()


class Migration(migrations.Migration):

    dependencies = [
        ('vfse', '0023_alter_comment_options'),
    ]

    operations = [
        migrations.RunPython(default_categories),
    ]
