# Generated by Django 4.1 on 2022-09-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfse', '0025_alter_document_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='categories',
            field=models.ManyToManyField(related_name='documents', to='vfse.category'),
        ),
    ]
