# Generated by Django 3.2.8 on 2021-11-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailbackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='email',
            name='html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
