name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "17"
          cache: npm
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9.7
          cache: pip
      - run: npm install
      - uses: pre-commit/action@v2.0.3
