
name: -send-message-slack

on:
  workflow_call:
    inputs:
      slack_message:
        required: true
        type: string
    secrets:
      SLACK_WEBHOOK:
        required: true

jobs:
  send_message_to_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.22.0
        with:
          payload: |
            {
              "text": "${{ inputs.slack_message }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
      - run: |
          echo "${{inputs.slack_message}}":
