name: deploy-to-staging
on:
  pull_request:
    types:
      - closed

jobs:
  pre-commit_and_test:
    uses: ./.github/workflows/ci.yml
  deploy:
    needs: pre-commit_and_test
    name: "Deploy to staging"
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.STAGING_SSH_USER }}
          SSH_KEY: ${{ secrets.STAGING_SSH_KEY }}
          SSH_HOST: ${{ secrets.STAGING_SSH_HOST }}

      - name: Pull the latest code to the staging environment
        run: ssh staging 'cd vfse && git pull'

      - name: Start containers
        run: |
          ssh staging 'cd vfse && docker-compose -f docker-compose.staging.yml build'
          ssh staging 'cd vfse && docker-compose -f docker-compose.staging.yml up -d'
          ssh staging 'cd vfse && docker-compose -f docker-compose.staging.yml exec app ./manage.py migrate'
          ssh staging 'cd vfse && docker-compose -f docker-compose.staging.yml exec app npm run build'
          ssh staging 'cd vfse && docker-compose -f docker-compose.staging.yml exec app ./manage.py collectstatic --noinput'

      - name: Test the App
        run: |
          ssh staging 'if [ $( docker ps -a | grep vfse | wc -l ) -gt 0 ]; then  echo "vfse exists"; else   echo "vfse does not exist" && raise error; fi'
  ready-for-qa:
    needs: deploy
    uses: ./.github/workflows/ready-for-qa.yml