name: 'Add label to stale issues and PRs'
on:
  schedule:
    - cron: '0 0 */3 * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    steps:
      - uses: actions/stale@v5
        with:
          stale-issue-message: 'A label is added because there has been no activity on this issue for three days. Manually remove the label or comment on this issue to remove it.'
          stale-pr-message: 'This PR is stale because it has been open 3 days with no activity. Remove stale label or comment  to remove stale label.'
          days-before-issue-stale: 3
          days-before-pr-stale: 3
          days-before-close: -1
